# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode7.3
language: objective-c
cache: cocoapods
podfile: Example/Podfile
before_install:
- gem install cocoapods # Since Travis is not always on latest version
- pod repo update
- pod install --project-directory=Example
script:
- set -o pipefail && xcodebuild test -workspace Example/CDYelpKit.xcworkspace -scheme CDYelpKit-Example -sdk iphonesimulator9.3 ONLY_ACTIVE_ARCH=NO | xcpretty
- pod lib lint

language: objective-c
osx_image: xcode8

cache: cocoapods
podfile: Example/Podfile

env:
  global:
  - LC_CTYPE=en_US.UTF-8
  - LANG=en_US.UTF-8
  - WORKSPACE=Example/CDYelpKit.xcworkspace
  - IOS_FRAMEWORK_SCHEME="CDYelpKit"
  - IOS_SDK=iphonesimulator10.0
  - EXAMPLE_SCHEME="CDYelpKit-Example"
  matrix:
    - DESTINATION="OS=10.0,name=iPhone SE"      SCHEME="$IOS_FRAMEWORK_SCHEME"  SDK="$IOS_SDK"  BUILD_FRAMEWORK="YES"   BUILD_EXAMPLE="YES" RUN_TESTS="YES" POD_LINT="YES"
    - DESTINATION="OS=10.0,name=iPhone 7 Plus"  SCHEME="$IOS_FRAMEWORK_SCHEME"  SDK="$IOS_SDK"  BUILD_FRAMEWORK="YES"   BUILD_EXAMPLE="YES" RUN_TESTS="YES" POD_LINT="NO"
    - DESTINATION="OS=10.0,name=iPhone 7"       SCHEME="$IOS_FRAMEWORK_SCHEME"  SDK="$IOS_SDK"  BUILD_FRAMEWORK="YES"   BUILD_EXAMPLE="YES" RUN_TESTS="YES" POD_LINT="NO"
    
    - DESTINATION="OS=9.3,name=iPhone 6s Plus"  SCHEME="$IOS_FRAMEWORK_SCHEME"  SDK="$IOS_SDK"  BUILD_FRAMEWORK="YES"   BUILD_EXAMPLE="YES" RUN_TESTS="YES" POD_LINT="NO"
    - DESTINATION="OS=9.3,name=iPhone 6s"       SCHEME="$IOS_FRAMEWORK_SCHEME"  SDK="$IOS_SDK"  BUILD_FRAMEWORK="YES"   BUILD_EXAMPLE="YES" RUN_TESTS="YES" POD_LINT="NO"
    - DESTINATION="OS=9.3,name=iPhone 6 Plus"   SCHEME="$IOS_FRAMEWORK_SCHEME"  SDK="$IOS_SDK"  BUILD_FRAMEWORK="YES"   BUILD_EXAMPLE="YES" RUN_TESTS="YES" POD_LINT="NO"
    - DESTINATION="OS=9.3,name=iPhone 6"        SCHEME="$IOS_FRAMEWORK_SCHEME"  SDK="$IOS_SDK"  BUILD_FRAMEWORK="YES"   BUILD_EXAMPLE="YES" RUN_TESTS="YES" POD_LINT="NO"
    - DESTINATION="OS=9.3,name=iPhone 5s"       SCHEME="$IOS_FRAMEWORK_SCHEME"  SDK="$IOS_SDK"  BUILD_FRAMEWORK="YES"   BUILD_EXAMPLE="YES" RUN_TESTS="YES" POD_LINT="NO"
    - DESTINATION="OS=9.3,name=iPhone 5"        SCHEME="$IOS_FRAMEWORK_SCHEME"  SDK="$IOS_SDK"  BUILD_FRAMEWORK="YES"   BUILD_EXAMPLE="YES" RUN_TESTS="YES" POD_LINT="NO"
    - DESTINATION="OS=9.3,name=iPhone 4s"       SCHEME="$IOS_FRAMEWORK_SCHEME"  SDK="$IOS_SDK"  BUILD_FRAMEWORK="YES"   BUILD_EXAMPLE="YES" RUN_TESTS="YES" POD_LINT="NO"
before_install:
  - gem install cocoapods --pre --no-rdoc --no-ri --no-document --quiet
  - pod repo update --silent
  - pod install --project-directory=Example
script:
  - set -o pipefail
  - xcodebuild -version
  - xcodebuild -showsdks

  # Build Framework in Debug if specified
  - if [ $BUILD_FRAMEWORK == "YES" ]; then
      xcodebuild -workspace "$WORKSPACE" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO build | xcpretty;
    fi

  # Build Framework in Release if specified
  - if [ $BUILD_FRAMEWORK == "YES" ]; then
      xcodebuild -workspace "$WORKSPACE" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Release ONLY_ACTIVE_ARCH=NO build | xcpretty;
    fi

  # Build Example in Debug if specified
  - if [ $BUILD_EXAMPLE == "YES" ]; then
      xcodebuild -workspace "$WORKSPACE" -scheme "$EXAMPLE_SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO build | xcpretty;
    fi

  # Build Example in Release if specified
  - if [ $BUILD_EXAMPLE == "YES" ]; then
      xcodebuild -workspace "$WORKSPACE" -scheme "$EXAMPLE_SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Release ONLY_ACTIVE_ARCH=NO build | xcpretty;
    fi
    
  # Run tests if specified
  - if [ $RUN_TESTS == "YES" ]; then
      xcodebuild -workspace "$WORKSPACE" -scheme "$EXAMPLE_SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO test | xcpretty;
    else
      xcodebuild -workspace "$WORKSPACE" -scheme "$EXAMPLE_SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO build | xcpretty;
    fi

  # Run `pod lib lint` if specified
  - if [ $POD_LINT == "YES" ]; then
      pod lib lint;
    fi